-- Strategic Intelligence Layer
-- Competitive monitoring, trend tracking, and AI-powered insights for campaign optimization

-- Create competitive_posts table (track what competitors/influencers are posting)
CREATE TABLE vantage.competitive_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES vantage.workspaces(id) ON DELETE CASCADE,

  -- Source information
  source_platform text NOT NULL CHECK (source_platform IN ('x', 'linkedin', 'reddit')),
  source_account_id text NOT NULL, -- Twitter ID, LinkedIn profile, Reddit username
  source_account_name text NOT NULL,
  source_account_url text,

  -- Post metadata
  post_id text NOT NULL,
  post_url text NOT NULL,
  post_title text,
  post_content text,
  posted_at timestamp with time zone,

  -- Performance metrics (collected at fetch time)
  impressions integer DEFAULT 0,
  engagements integer DEFAULT 0,
  likes integer DEFAULT 0,
  reposts integer DEFAULT 0,
  replies integer DEFAULT 0,
  follows integer DEFAULT 0,

  -- AI-extracted insights
  -- content_themes: ["product launch", "educational", "engagement hook", ...]
  content_themes jsonb DEFAULT '[]'::jsonb,

  -- sentiment: "positive" | "neutral" | "negative"
  sentiment text CHECK (sentiment IN ('positive', 'neutral', 'negative')),

  -- virality_indicators: { engagement_rate, repost_rate, trend_velocity }
  virality_indicators jsonb,

  -- Relevance to workspace brand (0-1 score)
  relevance_score decimal(3,2),

  -- Metadata
  tracked_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create trending_content table (aggregated trends across platforms)
CREATE TABLE vantage.trending_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES vantage.workspaces(id) ON DELETE CASCADE,

  -- Trend metadata
  trend_name text NOT NULL,
  trend_category text, -- "product_feature", "social_cause", "cultural_moment", "industry_shift"
  trend_status text NOT NULL DEFAULT 'emerging' CHECK (trend_status IN ('emerging', 'peak', 'declining', 'sustained')),

  -- Time window this trend was detected in
  detected_at timestamp with time zone NOT NULL,
  peak_at timestamp with time zone,
  expected_end_at timestamp with time zone,

  -- Aggregated metrics across posts
  total_mentions integer DEFAULT 0,
  unique_sources integer DEFAULT 0, -- How many different accounts posted about it
  average_engagement_rate decimal(5,2),

  -- Related posts
  -- example_posts: [{ post_id, platform, source_account, url, engagement_rate }]
  example_posts jsonb DEFAULT '[]'::jsonb,

  -- AI insights
  -- key_messaging: ["message 1", "message 2", ...]
  key_messaging jsonb DEFAULT '[]'::jsonb,

  -- sentiment_breakdown: { positive: 0.7, neutral: 0.2, negative: 0.1 }
  sentiment_breakdown jsonb,

  -- Relevance to workspace
  relevance_score decimal(3,2),
  -- use_cases: ["content_idea", "partnership", "thought_leadership"]
  recommended_use_cases jsonb DEFAULT '[]'::jsonb,

  -- Metadata
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create intelligence_insights table (AI-generated strategic recommendations)
CREATE TABLE vantage.intelligence_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES vantage.workspaces(id) ON DELETE CASCADE,
  campaign_id uuid REFERENCES vantage.campaigns(id) ON DELETE SET NULL,

  -- Insight type
  insight_type text NOT NULL CHECK (insight_type IN (
    'competitive_gap',           -- We're missing a messaging angle competitors own
    'opportunity',               -- Emerging trend we can capitalize on
    'benchmark',                 -- Our performance vs. competitors
    'optimization',              -- How to improve current campaign
    'audience_insight',          -- What our audience cares about
    'format_recommendation',     -- Recommended content formats
    'timing_recommendation'      -- Best times/days to post
  )),

  -- Insight content
  title text NOT NULL,
  description text NOT NULL,
  evidence_sources jsonb, -- [{ source_platform, source_account, post_url, supporting_metric }]

  -- Actionable recommendations
  recommended_actions jsonb, -- [{ action, expected_impact, priority }]

  -- Confidence level (0-100)
  confidence_score integer CHECK (confidence_score >= 0 AND confidence_score <= 100),

  -- Impact projection
  -- expected_impact: { engagement_increase: 0.25, reach_increase: 0.40, virality_lift: 0.15 }
  expected_impact jsonb,

  -- Generated by LLM
  generated_by text, -- "claude" | "gpt-4o" | "grok"
  generated_at timestamp with time zone DEFAULT now() NOT NULL,

  -- Optional: dismissed or actioned
  status text DEFAULT 'new' CHECK (status IN ('new', 'reviewed', 'actioned', 'dismissed')),
  actioned_at timestamp with time zone,

  -- Metadata
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create competitive_benchmarks table (periodic snapshots of competitor performance)
CREATE TABLE vantage.competitive_benchmarks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES vantage.workspaces(id) ON DELETE CASCADE,

  -- Benchmark period
  period_start date NOT NULL,
  period_end date NOT NULL,

  -- Competitor cohort
  -- competitors: [{ platform, account_id, account_name, ... }]
  competitors jsonb NOT NULL,

  -- Our metrics in period
  our_impressions integer,
  our_engagements integer,
  our_average_engagement_rate decimal(5,2),
  our_reach_growth integer,
  our_follower_growth integer,

  -- Competitor averages
  competitor_avg_impressions integer,
  competitor_avg_engagements integer,
  competitor_avg_engagement_rate decimal(5,2),
  competitor_avg_reach_growth integer,
  competitor_avg_follower_growth integer,

  -- Gap analysis
  -- gaps: { engagement_rate: -0.05, reach_growth: -0.10, strength_areas: ["thought_leadership"] }
  gaps jsonb,

  -- Recommendations based on benchmark
  -- recommendations: [{ area, current_vs_competitor, suggested_tactic }]
  recommendations jsonb DEFAULT '[]'::jsonb,

  -- Metadata
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create monitoring_sources table (track which accounts/topics we're monitoring)
CREATE TABLE vantage.monitoring_sources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES vantage.workspaces(id) ON DELETE CASCADE,

  -- Source details
  source_type text NOT NULL CHECK (source_type IN ('competitor', 'influencer', 'industry_leader', 'partner', 'keyword')),
  source_platform text NOT NULL CHECK (source_platform IN ('x', 'linkedin', 'reddit')),
  source_identifier text NOT NULL, -- Account ID, username, or keyword
  source_name text,
  source_url text,

  -- Monitoring config
  is_active boolean DEFAULT true,
  monitor_since timestamp with time zone DEFAULT now(),

  -- Priority level
  priority text DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),

  -- Category/tags for filtering
  -- categories: ["direct_competitor", "adjacent_market", "thought_leader"]
  categories jsonb DEFAULT '[]'::jsonb,

  -- Metadata
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Indexes for performance
CREATE INDEX idx_competitive_posts_workspace_id ON vantage.competitive_posts(workspace_id);
CREATE INDEX idx_competitive_posts_platform ON vantage.competitive_posts(source_platform);
CREATE INDEX idx_competitive_posts_posted_at ON vantage.competitive_posts(posted_at);
CREATE INDEX idx_competitive_posts_relevance ON vantage.competitive_posts(relevance_score DESC);

CREATE INDEX idx_trending_content_workspace_id ON vantage.trending_content(workspace_id);
CREATE INDEX idx_trending_content_status ON vantage.trending_content(trend_status);
CREATE INDEX idx_trending_content_detected_at ON vantage.trending_content(detected_at DESC);
CREATE INDEX idx_trending_content_relevance ON vantage.trending_content(relevance_score DESC);

CREATE INDEX idx_intelligence_insights_workspace_id ON vantage.intelligence_insights(workspace_id);
CREATE INDEX idx_intelligence_insights_campaign_id ON vantage.intelligence_insights(campaign_id);
CREATE INDEX idx_intelligence_insights_type ON vantage.intelligence_insights(insight_type);
CREATE INDEX idx_intelligence_insights_status ON vantage.intelligence_insights(status);
CREATE INDEX idx_intelligence_insights_created_at ON vantage.intelligence_insights(created_at DESC);

CREATE INDEX idx_competitive_benchmarks_workspace_id ON vantage.competitive_benchmarks(workspace_id);
CREATE INDEX idx_competitive_benchmarks_period ON vantage.competitive_benchmarks(period_start, period_end);

CREATE INDEX idx_monitoring_sources_workspace_id ON vantage.monitoring_sources(workspace_id);
CREATE INDEX idx_monitoring_sources_active ON vantage.monitoring_sources(is_active);

-- Comments
COMMENT ON TABLE vantage.competitive_posts IS 'Tracked posts from competitors, influencers, and industry leaders across platforms';
COMMENT ON TABLE vantage.trending_content IS 'Aggregated trends detected across competitive_posts; used for opportunity identification';
COMMENT ON TABLE vantage.intelligence_insights IS 'AI-generated strategic insights and recommendations for campaign optimization';
COMMENT ON TABLE vantage.competitive_benchmarks IS 'Periodic performance snapshots comparing our metrics to competitor averages';
COMMENT ON TABLE vantage.monitoring_sources IS 'Accounts and keywords to monitor for competitive intelligence gathering';
COMMENT ON COLUMN vantage.competitive_posts.virality_indicators IS 'Metrics to identify viral patterns: { engagement_rate, repost_rate, trend_velocity }';
COMMENT ON COLUMN vantage.trending_content.trend_status IS 'Lifecycle stage: emerging (gaining traction), peak (maximum engagement), declining, sustained';
COMMENT ON COLUMN vantage.intelligence_insights.insight_type IS 'Category of insight: competitive gap, emerging opportunity, benchmark analysis, optimization tip, etc.';
COMMENT ON COLUMN vantage.competitive_benchmarks.competitors IS 'Competitor cohort definition; updated periodically to match current market';
